"""fix created_by set removed nullable=False

Revision ID: d0c86574f88f
Revises: a6ddf4582426
Create Date: 2025-12-04 11:51:06.030073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0c86574f88f'
down_revision: Union[str, Sequence[str], None] = 'a6ddf4582426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
